SCREEN_WIDTH = 1280         # Default: 1280
SCREEN_HEIGHT = 720         # Default: 720
FPS_CAP = 60                # Default: 60
PLAYER_RADIUS = 20          # Default: 20
LINE_WIDTH = 2              # Default: 2
PLAYER_TURN_SPEED = 300     # Default: 300
PLAYER_SPEED = 200          # Default: 200
ASTEROID_MIN_RADIUS = 20    # Default: 20
ASTEROID_KINDS = 3          # Default: 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8   # Default: 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS # Default: ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 5             # Default: 5
PLAYER_SHOOT_SPEED = 500    # Default: 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3 # Default: 0.3